### ISSUE TITLE
账号密码

### ISSUE THREAD

**Issue by guoshizhan** [jaslli/vue-admin#1]
请问一下博主，账号密码是什么

**Comment by whyneh** [comment]
还在开发中，后端我也还没上传，你可以写个接口先返回一些数据

**Comment by whyneh** [comment]
一起学习

**Comment by guoshizhan** [comment]
> 一起学习

**Comment by guoshizhan** [comment]
> 还在开发中，后端我也还没上传，你可以写个接口先返回一些数据

好的

**Comment by guoshizhan** [comment]
我现在写了一个博客系统，想实现前后端分离，所以需要参考一下大佬的vue前端

这是我的博客地址：https://gitee.com/guoshizhan/spring-boot-blog-lts

**Comment by whyneh** [comment]
我也是主后端的，都是学着写的。。
你可能就只能看看一些功能设计了。
这个是后端管理系统的UI，博客界面的在vue-blog那个仓库，后端的在blog这个仓库
比较完善的你可以看一下这个大佬
https://github.com/X1192176811/blog
